name: Publish to Marketplace

on:
  push:
    branches: [ github-actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm i -g vsce
      - run: npm ci
      - run: vsce -V
