name: Publish to Marketplace

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm i -g vsce
      - run: npm ci
      - run: vsce publish -p ${{ secrets.VSCE_TOKEN }}
