name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release Type'
        required: true
        type: choice
        default: 'patch'
        options:
          - patch
          - minor
          - major
      releaseChannel:
        description: 'Release Channel'
        required: true
        type: choice
        default: stable
        options:
          - stable
          - edge
      publishMarketplace:
        description: 'Publish on Visual Studio Marketplace?'
        required: true
        type: choice
        default: 'yes'
        options:
          - 'yes'
          - 'no'
      publishOpenVSX:
        description: 'Publish on Open VSX Registry?'
        required: true
        type: choice
        default: 'yes'
        options:
          - 'yes'
          - 'no'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Setup Node version
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci && cd frontend && npm ci

