name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release Type'
        required: true
        type: choice
        default: 'patch'
        options:
          - patch
          - minor
          - major
      releaseChannel:
        description: 'Release Channel'
        required: true
        type: choice
        default: stable
        options:
          - stable
          - edge
      publishMarketplace:
        description: 'Publish on Visual Studio Marketplace?'
        required: true
        type: choice
        default: 'yes'
        options:
          - 'yes'
          - 'no'
      publishOpenVSX:
        description: 'Publish on Open VSX Registry?'
        required: true
        type: choice
        default: 'yes'
        options:
          - 'yes'
          - 'no'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "release-bot"
          git config --global user.email "szoftverhiba+release-bot@gmail.com"

      - name: Get Current Version Number
        run: |
          CURRENT_VERSION=$(npm pkg get version | cut -d'"' -f 2)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          echo $CURRENT_VERSION

      - name: Setup Node version
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci && cd frontend && npm ci

      - name: Set version in CHANGELOG
        run: node scripts/update-changelog.mjs

      - name: Publish to Visual Studio Marketplace (Edge)
        run: echo "Publish to Marketplace"
        if: ${{ github.event.inputs.publishMarketplace == 'yes' && github.event.inputs.releaseChannel == 'edge' }}

