name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release Type'
        required: true
        type: choice
        default: 'patch'
        options:
          - patch
          - minor
          - major
      releaseChannel:
        description: 'Release Channel'
        required: true
        type: choice
        default: stable
        options:
          - stable
          - edge
      publishMarketplace:
        description: 'Publish on Visual Studio Marketplace?'
        required: true
        type: choice
        default: 'yes'
        options:
          - 'yes'
          - 'no'
      publishOpenVSX:
        description: 'Publish on Open VSX Registry?'
        required: true
        type: choice
        default: 'yes'
        options:
          - 'yes'
          - 'no'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "release-bot"
          git config --global user.email "szoftverhiba+release-bot@gmail.com"

      - name: Get Current Version Number
        run: |
          CURRENT_VERSION=$(npm pkg get version | cut -d'"' -f 2)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          echo $CURRENT_VERSION

      - name: Setup Node version
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            frontend/package-lock.json

      - name: Install dependencies
        run: npm ci && cd frontend && npm ci

      - name: Bump version (Edge)
        run: |
          RELEASE_VERSION=$(npx semver -i prerelease --preid=edge $CURRENT_VERSION)
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          npm version $RELEASE_VERSION --git-tag-version=false
        if: ${{ github.event.inputs.releaseChannel == 'edge' }}

      - name: Bump version (Stable)
        run: |
          RELEASE_VERSION=$(npx semver $CURRENT_VERSION -i github.event.inputs.releaseType)
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          npm version $RELEASE_VERSION --git-tag-version=false
        if: ${{ github.event.inputs.releaseChannel == 'stable' }}

      - name: Update Changelog (Stable)
        run: node scripts/update-changelog.mjs
        if: ${{ github.event.inputs.releaseChannel == 'stable' }}

      - name: Tagging
        run: |
          git add .
          git commit -m "$RELEASE_VERSION"
          git tag -a v$RELEASE_VERSION -m "$RELEASE_VERSION"

      - name: Push tag
        run: |
          git push
          git push origin --tags

      - run: |
          export GIT_TAG=$(git describe --tags --abbrev=0)
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV

      - name: Update edge version (Edge)
        run: node scripts/update-edge-version.js
        if: ${{ github.event.inputs.publishMarketplace == 'yes' && github.event.inputs.releaseChannel == 'edge' }}

      - name: Build package (Edge)
        run: npx vsce package --pre-release --out "./commit-message-editor-$RELEASE_VERSION.vsix"
        if: ${{ github.event.inputs.releaseChannel == 'edge' }}

      - name: Build package (Stable)
        run: npx vsce package
        if: ${{ github.event.inputs.releaseChannel == 'stable' }}

      - name: Publish to Visual Studio Marketplace (Edge)
        run: npx vsce publish --packagePath "./commit-message-editor-$RELEASE_VERSION.vsix" --pat ${{ secrets.VSCE_TOKEN }} --pre-release
        if: ${{ github.event.inputs.publishMarketplace == 'yes' && github.event.inputs.releaseChannel == 'edge' }}

      - name: Publish to Visual Studio Marketplace (Stable)
        run: npx vsce publish --packagePath "./commit-message-editor-$RELEASE_VERSION.vsix" --pat ${{ secrets.VSCE_TOKEN }}
        if: ${{ github.event.inputs.publishMarketplace == 'yes' && github.event.inputs.releaseChannel == 'stable' }}

      # - name: Publish to Open VSX Registry (Edge)
      #   uses: HaaLeo/publish-vscode-extension@v1
      #   if: ${{ github.event.inputs.publishOpenVSX == 'yes' && github.event.inputs.releaseChannel == 'edge' }}
      #   with:
      #     preRelease: true
      #     pat: ${{ secrets.OPEN_VSX_TOKEN }}
      #     extensionFile: ./commit-message-editor-${{ env.RELEASE_VERSION }}.vsix

      - name: Publish to Open VSX Registry (Stable)
        uses: HaaLeo/publish-vscode-extension@v1
        if: ${{ github.event.inputs.publishOpenVSX == 'yes' && github.event.inputs.releaseChannel == 'stable' }}
        with:
          preRelease: false
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: ./commit-message-editor-${{ env.RELEASE_VERSION }}.vsix

      - name: Github Release (Edge)
        uses: ncipollo/release-action@v1
        if: ${{ github.event.inputs.releaseChannel == 'edge' }}
        with:
          artifacts: './commit-message-editor-*'
          prerelease: true
          draft: true
          tag: ${{ env.GIT_TAG }}
          generateReleaseNotes: true

      - name: Github Release (Stable)
        uses: ncipollo/release-action@v1
        if: ${{ github.event.inputs.releaseChannel == 'stable' }}
        with:
          artifacts: './commit-message-editor-*'
          prerelease: false
          draft: true
          tag: ${{ env.GIT_TAG }}
          generateReleaseNotes: true
