name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release Type'
        required: true
        type: choice
        default: 'patch'
        options:
          - patch
          - minor
          - major
      releaseChannel:
        description: 'Release Channel'
        required: true
        type: choice
        default: stable
        options:
          - stable
          - edge
      publishMarketplace:
        description: 'Publish on Visual Studio Marketplace?'
        required: true
        type: choice
        default: 'yes'
        options:
          - 'yes'
          - 'no'
      publishOpenVSX:
        description: 'Publish on Open VSX Registry?'
        required: true
        type: choice
        default: 'yes'
        options:
          - 'yes'
          - 'no'
